game.splash("We are going to calculate the area of the trapezoid.")
base1 = game.ask_for_number("enter base1 in cm")
base2 = game.ask_for_number("enter base2 in cm")
height = game.ask_for_number("enter height in cm")
area = base1 + base2 / (2 * height)
game.splash("the area of the trapezoid is base1 at cm " + ("" + str(base1)) + "base2 at cm" + ("" + str(base2)) + "height at cm" + ("" + str(height)) + "and area at cm" + ("" + str(area)))
base1 = game.ask_for_number("enter base1 in cm")
base2 = game.ask_for_number("enter base2 in cm")
height = game.ask_for_number("enter height in cm")
area = base1 + base2 / (2 * height)
game.splash("the area of the trapezoid is base1 at cm " + ("" + str(base1)) + "base2 at cm" + ("" + str(base2)) + "height at cm" + ("" + str(height)) + "and area at cm" + ("" + str(area)))