game.splash("We are going to calculate the area of the trapezoid.")
let base1 = game.askForNumber("enter base1 in cm")
let base2 = game.askForNumber("enter base2 in cm")
let height = game.askForNumber("enter height in cm")
let area = base1 + base2 / (2 * height)
game.splash("the area of the trapezoid is base1 at cm " + ("" + ("" + base1)) + "base2 at cm" + ("" + ("" + base2)) + "height at cm" + ("" + ("" + height)) + "and area at cm" + ("" + ("" + area)))
base1 = game.askForNumber("enter base1 in cm")
base2 = game.askForNumber("enter base2 in cm")
height = game.askForNumber("enter height in cm")
area = base1 + base2 / (2 * height)
game.splash("the area of the trapezoid is base1 at cm " + ("" + ("" + base1)) + "base2 at cm" + ("" + ("" + base2)) + "height at cm" + ("" + ("" + height)) + "and area at cm" + ("" + ("" + area)))
